export const compilerInfo = {
  C: {
    info: "C is a general-purpose, procedural programming language. It is one of the most widely used languages for system programming.",
    sections: {
      code: "C code is written in text editors and compiled using tools like GCC or Clang.",
      compile:
        "To compile C code, use a C compiler to convert it into machine code that the computer can execute.",
      debug:
        "Debugging C code can be done using tools like GDB, which help identify and fix issues.",
      about:
        "C programming is crucial for system-level programming, embedded systems, and performance-critical applications.",
      whyLearn:
        "Learning C helps you understand the fundamentals of programming and computer architecture.",
      syntax:
        "C syntax consists of functions, variables, operators, loops, conditionals, and more.",
      tutorials:
        "C tutorials are available online, covering everything from basic syntax to advanced concepts.",
      howItWorks:
        "NextLeap's C compiler compiles the code in real-time, allowing you to see results instantly.",
      writingCode:
        "You can write C code online using any text editor or IDE that supports C syntax.",
      realTime:
        "Real-time compilation gives immediate feedback as you write your code.",
      interactiveDebugging:
        "Our C compiler allows for interactive debugging to help resolve issues in your code.",
      sharing:
        "Share your C code with others through links generated by the online compiler for easy collaboration.",
    },
    faqs: [
      {
        question: "How do I run a C program?",
        answer: "To run a C program, you need a C compiler like GCC.",
      },
      {
        question: "What is a C compiler?",
        answer:
          "A C compiler translates C code into machine code that the computer can execute.",
      },
    ],
  },
  "C++": {
    info: "C++ is a general-purpose programming language created as an extension of C. It supports object-oriented, generic, and functional programming.",
    sections: {
      code: "C++ code is written in text editors or IDEs and compiled using a C++ compiler.",
      compile:
        "To compile C++ code, you need a C++ compiler like GCC or Clang.",
      debug:
        "You can debug C++ programs using GDB or IDE-specific debuggers like those in Visual Studio or Code::Blocks.",
      about:
        "C++ is widely used in game development, systems programming, and large-scale applications.",
      whyLearn:
        "Learning C++ gives you a deeper understanding of low-level computing and memory management.",
      syntax:
        "C++ syntax includes classes, objects, inheritance, polymorphism, and templates.",
      tutorials:
        "There are many resources online for learning C++, ranging from beginner to advanced topics.",
      howItWorks:
        "NextLeap's C++ compiler compiles and runs your code in real-time, helping you to learn faster.",
      writingCode:
        "Writing C++ code is straightforward with text editors or specialized IDEs like Visual Studio or Eclipse.",
      realTime:
        "Our platform compiles and runs C++ code in real-time, displaying output immediately.",
      interactiveDebugging:
        "Interactive debugging allows you to step through your code and inspect variables at runtime.",
      sharing:
        "You can share your C++ code with others through generated links to foster collaboration.",
    },
    faqs: [
      {
        question: "What are the features of C++?",
        answer:
          "C++ supports classes, inheritance, polymorphism, templates, and more.",
      },
      {
        question: "What is an object in C++?",
        answer:
          "An object is an instance of a class in C++, encapsulating data and methods.",
      },
    ],
  },
  Java: {
    info: "Java is a high-level, class-based, object-oriented programming language designed to have few implementation dependencies.",
    sections: {
      code: "Java code is written in text editors or IDEs and compiled using the `javac` compiler.",
      compile:
        "To compile Java code, use the `javac` compiler to generate bytecode, which is run on the JVM (Java Virtual Machine).",
      debug:
        "You can debug Java programs using built-in debugging tools in IDEs like Eclipse or IntelliJ IDEA, or by using `jdb`.",
      about:
        "Java is widely used for web applications, Android development, and enterprise-level software.",
      whyLearn:
        "Learning Java helps you become proficient in object-oriented programming, and it is highly sought after in the software industry.",
      syntax:
        "Java syntax includes classes, objects, inheritance, interfaces, and exception handling.",
      tutorials:
        "There are many resources available online for Java, ranging from beginner to advanced topics.",
      howItWorks:
        "NextLeap's Java compiler compiles Java code to bytecode, which runs on the JVM in real-time, providing immediate results.",
      writingCode:
        "Java code is typically written using IDEs like IntelliJ IDEA or Eclipse, which provide syntax highlighting and debugging tools.",
      realTime:
        "Real-time compilation and execution allow immediate feedback as you write and test your Java code.",
      interactiveDebugging:
        "Interactive debugging tools are available in many IDEs, allowing you to step through your Java code.",
      sharing:
        "You can share your Java code through generated links to promote collaboration.",
    },
    faqs: [
      {
        question: "What is JVM?",
        answer:
          "JVM (Java Virtual Machine) is a virtual machine that allows Java programs to run on any device or operating system.",
      },
      {
        question: "How to handle exceptions in Java?",
        answer: "Java uses try-catch blocks to handle exceptions.",
      },
    ],
  },
  JavaScript: {
    info: "JavaScript is a versatile, high-level, interpreted programming language primarily used for building interactive web applications.",
    sections: {
      code: "JavaScript code is written in text editors or IDEs and can be run directly in web browsers or Node.js.",
      compile:
        "JavaScript code is interpreted rather than compiled. It is executed directly by web browsers or Node.js environments.",
      debug:
        "You can debug JavaScript using browser developer tools or Node.js debugger tools.",
      about:
        "JavaScript is used extensively in web development for both front-end and back-end programming.",
      whyLearn:
        "Learning JavaScript opens up opportunities in web development, where it is the language of the web.",
      syntax:
        "JavaScript syntax includes variables, functions, arrays, objects, loops, conditionals, and event handling.",
      tutorials:
        "There are numerous tutorials online that help you get started with JavaScript, from basic syntax to complex frameworks like React.",
      howItWorks:
        "NextLeap's JavaScript compiler provides real-time execution of JavaScript code, allowing quick feedback on your script.",
      writingCode:
        "JavaScript is written in code editors like VSCode or Sublime Text, which provide syntax highlighting and live preview features.",
      realTime:
        "Real-time execution helps you test and tweak your JavaScript code interactively.",
      interactiveDebugging:
        "Interactive debugging in browsers or IDEs helps you troubleshoot JavaScript code effectively.",
      sharing:
        "You can share your JavaScript code using online platforms, making collaboration simple.",
    },
    faqs: [
      {
        question: "What is Node.js?",
        answer:
          "Node.js is a JavaScript runtime environment that allows JavaScript to run on the server-side.",
      },
      {
        question: "How do I add interactivity to a website?",
        answer:
          "You can add interactivity using JavaScript, such as handling user events like clicks and form submissions.",
      },
    ],
  },
  "C#": {
    info: "C# (C-Sharp) is a modern, object-oriented programming language developed by Microsoft, used for developing a wide range of applications.",
    sections: {
      code: "C# code is typically written in Visual Studio or Visual Studio Code and compiled with the `csc` compiler.",
      compile:
        "To compile C# code, use the `csc` compiler, which generates an assembly (.exe) that runs on the .NET runtime.",
      debug:
        "C# can be debugged using the Visual Studio debugger, which allows stepping through code, inspecting variables, and more.",
      about:
        "C# is used in a variety of domains, including web applications (ASP.NET), game development (Unity), and enterprise software.",
      whyLearn:
        "Learning C# is highly valuable for working in the .NET ecosystem, especially for developing web apps, games, and enterprise solutions.",
      syntax:
        "C# syntax includes classes, methods, properties, and powerful features like LINQ and async programming.",
      tutorials:
        "Many C# tutorials are available, from beginner-friendly to more advanced, covering topics like .NET, ASP.NET, and Unity.",
      howItWorks:
        "NextLeap's C# compiler compiles the code and runs it in real-time, providing immediate results.",
      writingCode:
        "C# is written in IDEs like Visual Studio or JetBrains Rider, with comprehensive support for debugging and refactoring.",
      realTime:
        "Real-time execution allows immediate testing and feedback for C# applications.",
      interactiveDebugging:
        "C# debugging tools in Visual Studio help to inspect the program's state and fix issues during development.",
      sharing:
        "You can share C# code snippets and projects with others using GitHub or other version control systems.",
    },
    faqs: [
      {
        question: "What is the .NET framework?",
        answer:
          "The .NET framework is a software development platform used for building and running C# applications.",
      },
      {
        question: "What are delegates in C#?",
        answer:
          "Delegates are type-safe function pointers used to pass methods as arguments in C#.",
      },
    ],
  },
  Go: {
    info: "Go, also known as Golang, is an open-source programming language created by Google that is known for its simplicity, concurrency, and efficiency.",
    sections: {
      code: "Go code is written in text editors or IDEs like GoLand and compiled using the `go` command-line tool.",
      compile:
        "To compile Go code, use the `go build` command, which generates a binary executable.",
      debug:
        "Go can be debugged using tools like `delve`, an interactive debugger for Go programs.",
      about:
        "Go is widely used for backend development, cloud services, and scalable applications.",
      whyLearn:
        "Go is popular for building efficient, scalable applications and is especially useful for microservices.",
      syntax:
        "Go syntax is simple, focusing on clarity and efficiency. It includes functions, loops, and goroutines for concurrency.",
      tutorials:
        "Go tutorials are available for beginners and advanced learners, covering concurrency, web services, and cloud computing.",
      howItWorks:
        "NextLeap's Go compiler compiles and runs your Go code in real-time, providing immediate feedback.",
      writingCode:
        "Go code is typically written in text editors or Go-specific IDEs like GoLand.",
      realTime:
        "Real-time compilation provides feedback instantly when writing Go code.",
      interactiveDebugging:
        "Interactive debugging using `delve` helps you inspect and debug Go applications effectively.",
      sharing:
        "Share your Go projects with the community through GitHub and other version control platforms.",
    },
    faqs: [
      {
        question: "What are goroutines?",
        answer:
          "Goroutines are lightweight threads of execution in Go, used for concurrent programming.",
      },
      {
        question: "How does Go handle memory management?",
        answer:
          "Go uses garbage collection for automatic memory management, making development easier.",
      },
    ],
  },
  HTML: {
    info: "HTML (HyperText Markup Language) is the standard language for creating web pages and web applications.",
    sections: {
      code: "HTML code is written in text editors or IDEs and rendered by web browsers.",
      compile:
        "HTML is not compiled. It is interpreted directly by web browsers to render content on web pages.",
      debug:
        "You can debug HTML using browser developer tools, inspecting elements, and checking the console for errors.",
      about:
        "HTML provides the structure of web pages, using elements like headings, paragraphs, links, and images.",
      whyLearn:
        "Learning HTML is essential for creating websites and web applications, serving as the foundation of web development.",
      syntax:
        "HTML syntax consists of tags, attributes, and elements that define content structure on the web.",
      tutorials:
        "HTML tutorials range from beginner to advanced topics, covering everything from tags to responsive design.",
      howItWorks:
        "NextLeap's HTML editor allows you to see the rendered output of your HTML code in real-time.",
      writingCode:
        "HTML is written in code editors like Sublime Text, VSCode, or directly in IDEs like WebStorm.",
      realTime:
        "HTML code is rendered in real-time, allowing you to instantly see the output of your tags.",
      interactiveDebugging:
        "Use browser tools to inspect elements and debug HTML, ensuring your page is displayed as expected.",
      sharing:
        "HTML code can be shared by uploading it to hosting platforms or using collaborative tools like CodePen.",
    },
    faqs: [
      {
        question: "What are HTML tags?",
        answer:
          "HTML tags are elements used to define the structure and content of a web page.",
      },
      {
        question: "What is the difference between HTML and HTML5?",
        answer:
          "HTML5 is the latest version of HTML, including new features like multimedia support, local storage, and more.",
      },
    ],
  },
  Python: {
    info: "Python is an interpreted, high-level programming language known for its simplicity and readability.",
    sections: {
      Code: "Python code is written in text editors or IDEs and can be run directly using the `python` interpreter.",
      Compile:
        "Python is an interpreted language, so it doesn't require compilation. Code is executed line-by-line.",
      Debug:
        "You can debug Python using the built-in `pdb` debugger or IDE tools like PyCharm or VSCode.",
      About:
        "Python is widely used in web development, data science, automation, and artificial intelligence.",
      Why_Learn:
        "Learning Python is great for newcomers and is one of the most versatile languages for various applications.",
      syntax:
        "Python syntax emphasizes readability, using indentation to define code blocks.",
      tutorials:
        "Python tutorials are available for all levels, covering topics like web development, machine learning, and more.",
      howItWorks:
        "NextLeap's Python compiler allows real-time execution of Python code, providing quick results.",
      writingCode:
        "Python is typically written in text editors or IDEs like PyCharm, Jupyter Notebook, or VSCode.",
      realTime:
        "Python code is executed in real-time, making it easy to test small code snippets and check results instantly.",
      interactiveDebugging:
        "Interactive debugging in Python helps you step through your code and inspect variables.",
      sharing:
        "Share your Python code through GitHub, Jupyter notebooks, or PythonAnywhere for online collaboration.",
    },
    faqs: [
      {
        question: "What is PEP 8?",
        answer:
          "PEP 8 is the official style guide for Python code, defining conventions for readability.",
      },
      {
        question: "What are Python decorators?",
        answer:
          "Python decorators are a way to modify or extend the functionality of a function or method.",
      },
    ],
  },
};
